baseURL = "https://programmeriosif.github.io/pc-components/"
languageCode = "en-us"
title = "Componentele unui calculator"
theme = "PaperMod"
[params]
ShowBreadCrumbs = false
ShowPostNavLinks = true
    [params.cover]
    linkFullImages = true